# Override settings for a debug build
baseUrl           = "https://soasis.org"
buildDrafts       = false
buildExpired      = false
buildFuture       = false
disableLiveReload = true

[minify]
  minifyOutput = true
