# Override settings for a debug build
baseUrl           = "http://localhost:1313"
buildDrafts       = true
buildExpired      = true
buildFuture       = true
disableLiveReload = false

[minify]
  minifyOutput = false
