# Default Hugo Parameters
baseURL           = "/"
languageCode      = "en-us"
title             = "Shepherd's Oasis"
author            = "Shepherd's Oasis, LLC"
theme             = "hugo-future-imperfect-slim"
enableGitInfo     = true
buildDrafts       = false
buildExpired      = false
buildFuture       = false
disableLiveReload = true

[minify]
  minifyOutput = true

# Future Imperfect Parameters
# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
DefaultContentLanguage  = "en"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[markup.highlight]
  anchorLineNos = true
  codeFences = true
  guessSyntax = false
  lineNoStart = 0
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  style = "dracula"
  tabWidth = 5

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  mainSections          = ["posts"]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "dracula"
  highlightjsLang       = ["c", "cpp", "c++", "haskell", "rust"]
  viewMorePostsLink     = "/posts/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "Built from a theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "Shepherd S."
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Shepherd's Oasis"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Shepherd's Oasis, LLC"
    paragraph             = "A software consulting, contracting, training, teaching and services company here to help you deliver the best quality for your business and your customers!"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.png"
      shape               = "circle"
      width               = ""
      alt                 = "Shepherd's Oasis, LLC"

  [params.sidebar]
    about               = "A contracting and consulting company ready to serve your business needs, locally or globally!"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Posts"
    identifier        = "posts"
    url               = "/posts/"
    pre               = "<i class='fas fa-blog'></i>"
    weight            = 4

  [[menu.main]]
    name              = "WG14 - ISO C"
    identifier        = "wg14"
    url               = "/wg14/"
    pre               = "<i class='fas fa-scroll'></i>"
    weight            = 6

[social]
  # Coding Communities
  github                = "soasis"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin_company      = "shepherdsoasis"
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = "ShepherdsOasis"
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "ShepherdsOasis"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = "inquiries@soasis.org"
